{% set name = "NRSS" %}
{% set version = "2025.06.14.01" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/NRSS/archive/{{ version }}.tar.gz
  sha256: c56e8450ab938af516ea4e16389f47b78120df6b2fae0587b694f0e794b4e049

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyhyperscattering >=0.2.10
    - numpy
    - scipy
    - scikit-image
    - pandas
    - matplotlib-base
    - h5py
    - xarray
    - bottleneck
    - cyrsoxs
test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - NRSS
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/NRSS/
  license: NIST-PD
  license_file: LICENSE
  summary: NIST RSoXS Simulation Suite


extra:
  recipe-maintainers:
    - pbeaucage
    - delongchamp
